# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e6aa3912d5b0dcff5b043c3d3233ed547f39ce5f1b00f89580589d8847edb4443003bb737a46433e5c211a7091e6452482d272a56e2ba2f1d0569dfb1c78880

test:
  secret_key_base: 49b734c06307fe36f613d907ed8a3536c0b28c695884e01a4817135620442f28873524c9d111980863a6bb66cac4ceff516faaba24ae9fec054135ef28ca7bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
